-- ----------------------------------------------------
-- SCRIPT MIGRACIÓN A ORACLE (Gestión Ecommerce)
-- ----------------------------------------------------

-- NOTA: Ejecutar conectado como SYSTEM o SYS (con SYSDBA)
-- Asegúrate de estar en la PDB correcta (ej. FREEPDB1).

-- ----------------------------------------------------
-- LIMPIEZA INICIAL (Reset)
-- ----------------------------------------------------
BEGIN
   FOR c IN (SELECT username FROM dba_users WHERE username IN ('ECCOMERCE_ADMIN', 'ECOMMERCE_APP')) LOOP
      EXECUTE IMMEDIATE 'DROP USER ' || c.username || ' CASCADE';
   END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ----------------------------------------------------
-- CREACIÓN DE USUARIOS
-- ----------------------------------------------------

-- USUARIO PROPIETARIO (Dueño de las tablas)
CREATE USER ECCOMERCE_ADMIN IDENTIFIED BY AdminPass123$
DEFAULT TABLESPACE USERS 
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO ECCOMERCE_ADMIN;

-- USUARIO DE APLICACIÓN (Para conectar desde Java/C#)
CREATE USER ECOMMERCE_APP IDENTIFIED BY AppPass123$ DEFAULT TABLESPACE USERS QUOTA 0M ON USERS;

GRANT CREATE SESSION TO ECOMMERCE_APP;

-- Cambio al esquema del administrador para crear las tablas
ALTER SESSION SET CURRENT_SCHEMA = ECCOMERCE_ADMIN;


-- ----------------------------------------------------
-- CREACIÓN DE TABLAS (Sintaxis Oracle 12c+)
-- ----------------------------------------------------

-- ----------------------------------------------------
-- TABLA: INFORMACION_FISCAL
-- ----------------------------------------------------
CREATE TABLE informacion_fiscal (
    nif_cif     VARCHAR2(9)  NOT NULL,
    telefono    VARCHAR2(9)  NOT NULL UNIQUE,
    direccion   VARCHAR2(150) NOT NULL,
    CONSTRAINT pk_info_fiscal PRIMARY KEY (nif_cif)
);

-- ----------------------------------------------------
-- TABLA: CLIENTES
-- ----------------------------------------------------
CREATE TABLE clientes (
    nif_cif         VARCHAR2(9)  NOT NULL,
    nombre_completo VARCHAR2(100) NOT NULL UNIQUE,
    email           VARCHAR2(150) NOT NULL UNIQUE,
    fecha_creacion  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_clientes PRIMARY KEY (nif_cif),
    CONSTRAINT fk_clientes_info FOREIGN KEY (nif_cif) 
        REFERENCES informacion_fiscal(nif_cif) 
        ON DELETE CASCADE
    -- Nota: Oracle no soporta ON UPDATE CASCADE nativo
);

-- ----------------------------------------------------
-- TABLA: COMPRAS
-- ----------------------------------------------------
CREATE TABLE compras (
    id            INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_cliente    VARCHAR2(9), -- Permitimos NULL para el ON DELETE SET NULL
    direccion     VARCHAR2(150),
    fecha_compra  TIMESTAMP NOT NULL,
    estado        VARCHAR2(20) NOT NULL,
    precio_total  NUMBER(10, 2) NOT NULL,
    
    -- Simulación de ENUM con CHECK constraint
    CONSTRAINT chk_estado_compra CHECK (estado IN ('PENDIENTE', 'ENVIADO', 'ENTREGADO')),
    
    CONSTRAINT fk_compras_cliente FOREIGN KEY (id_cliente) 
        REFERENCES clientes(nif_cif)
        ON DELETE SET NULL 
    -- Nota: Cambiado de SET DEFAULT a SET NULL por compatibilidad
);

-- ----------------------------------------------------
-- TABLA: ARTICULOS
-- ----------------------------------------------------
CREATE TABLE articulos (
    id            INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR2(100) NOT NULL,
    descripcion   VARCHAR2(150),
    precio_actual NUMBER(10, 2) NOT NULL,
    stock         INTEGER NOT NULL
);

-- ----------------------------------------------------
-- TABLA: ARTICULO_COMPRA (Relación N:M)
-- ----------------------------------------------------
CREATE TABLE articulo_compra (
    id            INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    id_compra     INTEGER NOT NULL,
    id_articulo   INTEGER NOT NULL,
    unidades      INTEGER NOT NULL,
    precio_compra NUMBER(10, 2) NOT NULL,
    
    -- La clave única ahora es la combinación, pero la PK es el ID
    CONSTRAINT uq_articulo_compra UNIQUE (id_compra, id_articulo),
    
    CONSTRAINT fk_ac_compra FOREIGN KEY (id_compra) 
        REFERENCES compras(id), -- Quita el ON DELETE RESTRICT explícito si da guerra
        
    CONSTRAINT fk_ac_articulo FOREIGN KEY (id_articulo) 
        REFERENCES articulos(id)
);

-- ----------------------------------------------------
-- ASIGNACIÓN DE PERMISOS
-- ----------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON ECCOMERCE_ADMIN.informacion_fiscal TO ECOMMERCE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECCOMERCE_ADMIN.clientes TO ECOMMERCE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECCOMERCE_ADMIN.compras TO ECOMMERCE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECCOMERCE_ADMIN.articulos TO ECOMMERCE_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON ECCOMERCE_ADMIN.articulo_compra TO ECOMMERCE_APP;

COMMIT;